# 电池电量报告间隔时间单位是秒 //Battery report interval in seconds
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# 增加键盘消抖
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# 增加键盘的 BLE 无线电的发射功率，用解决延迟和左右通讯不佳的问题 //Increase BLE radio transmission power to address latency and poor communication issues
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# 更改键盘默认显示名称 //Change the default keyboard display name
CONFIG_ZMK_KEYBOARD_NAME="Corne"
# 用于解决 Windows 中与电池报告相关的错误 //Used to fix battery report related issues in Windows
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# oled相关配置 //OLED related configuration 
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
# Enable a widget to show words per minute
#CONFIG_ZMK_WIDGET_WPM_STATUS=n
#CONFIG_ZMK_WIDGET_LAYER_STATUS=n
#CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=n
#Bongo cat猫猫敲键盘动画 //Bongo cat keyboard animation
#CONFIG_ZMK_WIDGET_BONGO_CAT=y

# Nice Oled module config
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n #default is y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_GEM=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_MACOS=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_WINDOWS=n
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_BONGO_CAT_ONLY_CAPSLOCK=n
CONFIG_NICE_OLED_SHOW_SLEEP_ART_ON_IDLE=y
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=y
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n

#休眠相关配置 //Sleep related configuration
# Milliseconds of inactivity before entering idle state	(10 minute)
CONFIG_ZMK_IDLE_TIMEOUT=600000
# Enable deep sleep support	
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep (30 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# zmk studio相关配置 //ZMK Studio related configuration
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

#rgb相关配置 //RGB related configuration
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
#键盘进入空闲状态时关闭RGB //Turn off RGB when the keyboard enters idle state
CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
